markup:
  goldmark:
    renderer:
      unsafe: true
      
# enableGitInfo: true
disablePathToLower: true
baseURL: https://vibrant-booth-ad4728.netlify.app
languageCode: en-us
title: 'unnus '
params:
 socialThumbnail: /assets/images/default-card.png
 twitterHandle: "unnus_"
 author: Slimane M. Baghouri

 minify:
  disableSVG: false
