# the 2 lines below are bad practice and might introduce issues, might want to use disableKind instead. 
taxonomies:
  category: "categories" 

markup:
  goldmark:
    renderer:
      unsafe: true
      
# enableGitInfo: true
disablePathToLower: true
baseURL: https://unnus.com
languageCode: en-us
title: 'unnus '
params:
 socialThumbnail: https://unnus.com/assets/images/default-card.png
 twitterHandle: "unnus_"
 author: Slimane M. Baghouri

 minify:
  disableSVG: true

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
