---
new_page_extension: md
auto_deploy: false
admin_path: "/insider"
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/privte
  label: Privte
  create: all
  match: "**/*"
- type: directory
  path: content/medical
  label: Medical
  create: all
  match: "**/*"
- type: directory
  path: content/draft
  label: Draft
  create: all
  match: "**/*"
- type: directory
  path: content/case-studies
  label: Case studies
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.71.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.71.1
